language: android

jdk:
 - oraclejdk7

branches:
 only:
 - master

before_install:
 - chmod +x gradlew

android:
  components:
    - build-tools-21.1.2
    - android-21

script:
  - ./gradlew clean check -Dpre-dex=false

notifications:
  email: false

sudo: true